import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authConfig } from "@/lib/auth";
import { redirect } from "next/navigation";
import { AdminSidebar } from "@/components/navigations/adminSidebar";

export const metadata: Metadata = {
  title: "Admin Routes",
  description: "Generated by create next app",
};

export default async function AdminRoutesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authConfig);
  
  if (!session?.user?.isAdmin) {
    redirect("/");
  }
  return (
    <div className="min-h-screen flex flex-col md:flex-row bg-background">
      <AdminSidebar />
      <main className="flex-1 overflow-y-auto p-4 md:p-6 md:-ml-5 md:rounded-l-3xl z-50 bg-white w-full">
        <div className="mx-auto max-w-7xl">
          {children}
        </div>
      </main>
    </div>
  );
}
