import type { Metadata } from "next";
import { AdminSidebar } from "@/components/navigations/adminSidebar";

export const metadata: Metadata = {
  title: "Admin Routes",
  description: "Generated by create next app",
};

export default function AdminRoutesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex bg-background">
      <AdminSidebar />
      <main className="flex-1 overflow-y-auto p-6 -ml-5 rounded-l-3xl z-50 bg-white">
        <div className="mx-auto max-w-7xl">
          {children}
        </div>
      </main>
    </div>
  );
}
